---
title: "US Non-residential Construction Contractors by Trade"
author: "Dhruv Hirani"
date: 2021-10-15T21:13:14-05:00
categories: ["R"]
tags: ["contractors", "region", "construction"]
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE)
mykey= '4a8550fc62c4439e9629d8143ec319ec'

```

# Tables

This is a brief summary with R code of latest tables for contractor types by US regions.

## Retrieval of data from US Bureau of Labor Statistics using `blsAPI` library.

```{r datatable, warning=FALSE}
# install_github("mikeasilva/blsAPI")

library(blsAPI)
library(ggplot2)
library(dplyr)

payload <- list( 'seriesid' = c( "PCU236400236400"
                              , "PCU2364002364001"
                              , "PCU23640023640011"
                              , "PCU23640023640012"
                              , "PCU23640023640013"
                              , "PCU23640023640014"
                              , "PCU236400236400221"
                              , "PCU2364002364002211"
                              , "PCU2364002364002212"
                              , "PCU2364002364002213"
                              , "PCU2364002364002214"
                              , "PCU236400236400222"
                              , "PCU2364002364002221"
                              , "PCU2364002364002222"
                              , "PCU2364002364002223"
                              , "PCU2364002364002224"
                              , "PCU236400236400223"
                              , "PCU2364002364002231"
                              , "PCU2364002364002232"
                              , "PCU2364002364002233"
                              , "PCU2364002364002234"
                              , "PCU236400236400224"
                              , "PCU2364002364002241"
                              , "PCU2364002364002242"
                              , "PCU2364002364002243"
                              , "PCU2364002364002244"
                              )
              , 'startyear' = 2010
              , 'endyear' = 2030
              , 'registrationKey' = mykey
            )
response <- blsAPI(payload, 2, return_data_frame = TRUE)

response2 <- response

response2$seriesID <- as.factor(response2$seriesID)

levels(response2$seriesID) <-list(Contractors = "PCU236400236400"
                              , GC = "PCU2364002364001"
                              , GC_NE = "PCU23640023640011"
                              , GC_S = "PCU23640023640012"
                              , GC_MW = "PCU23640023640013"
                              , GC_W = "PCU23640023640014"
                              , MP = "PCU236400236400221"
                              , MP_NE = "PCU2364002364002211"
                              , MP_S = "PCU2364002364002212"
                              , MP_MW = "PCU2364002364002213"
                              , MP_NE = "PCU2364002364002214"
                              , EL = "PCU236400236400222"
                              , EL_NE = "PCU2364002364002221"
                              , EL_S = "PCU2364002364002222"
                              , EL_MW = "PCU2364002364002223"
                              , EL_W = "PCU2364002364002224"
                              , ROOF = "PCU236400236400223"
                              , ROOF_NE = "PCU2364002364002231"
                              , ROOF_S = "PCU2364002364002232"
                              , ROOF_MW = "PCU2364002364002233"
                              , ROOF_W = "PCU2364002364002234"
                              , CS = "PCU236400236400224"
                              , CS_NE = "PCU2364002364002241"
                              , CS_S = "PCU2364002364002242"
                              , CS_MW = "PCU2364002364002243"
                              , CS_W = "PCU2364002364002244"
                              )


response2$contractorType <- ifelse(grepl("MP_", response2$seriesID),"Mechanical & Plumbing", ifelse(
                                   grepl("EL_", response2$seriesID),"Electrical", ifelse(
                                    grepl("CS_", response2$seriesID), "Concrete and Structural",ifelse(
                                      grepl("ROOF_", response2$seriesID),"ROOFING", ifelse(
                                        grepl("GC", response2$seriesID),"General Contractor", "Contractor"))))
                                   )
                                         
response2$region <- ifelse(grepl("_NE", response2$seriesID),"Northeast", ifelse(
                                   grepl("_S", response2$seriesID),"South", ifelse(
                                    grepl("_MW", response2$seriesID), "Midwest", ifelse(
                                    grepl("_W", response2$seriesID), "West", "All")))
                                  )
response2$period <-gsub("M","",response2$period)

response2$date <- as.Date(with(response2, paste(year, period, "1", sep="-")), "%Y-%m-%d")


response2 %>% ggplot(response2, aes(date, value))
+ geomplot()

```

# Including Plots

You can also embed plots. See Figure \@ref(fig:pie) for example:

```{r pie, fig.cap='A fancy pie chart.', tidy=FALSE}
par(mar = c(0, 1, 0, 1))
pie(
  c(280, 60, 20),
  c('Sky', 'Sunny side of pyramid', 'Shady side of pyramid'),
  col = c('#0292D8', '#F7EA39', '#C4B632'),
  init.angle = -50, border = NA
)

```
